### ISSUE TITLE
mailtivarite time series classification for example mixture of categorical and continues data 

### ISSUE THREAD

**Issue by Sandy4321** [jayshah19949596/Machine-Learning#1]
will it work for 
mailtivarite time series classification for example mixture of categorical and continues data 
for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by jayshah19949596** [comment]
Yes, the algorithm will work on multivariate time series classification, you might have to do some kind of processing. This is not an issue in the repo. So, closing this.
